FROM --platform=$BUILDPLATFORM golang:1.20-alpine as build
ARG TARGETARCH
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=$TARGETARCH
COPY proxy /proxy
WORKDIR /proxy
RUN  go build -ldflags "-s -w" -o proxy main.go 
FROM --platform=$TARGETPLATFORM wbuntu/free-ask-internet:v0.0.1
COPY --from=build /proxy/proxy /app/proxy/proxy
COPY supervisor.d /etc/supervisor.d
EXPOSE 6789
EXPOSE 8000
